name: OMERO User Help Website
plugins:
  - jekyll-redirect-from
markdown: redcarpet
highlighter: rouge

omero:
  version: 5.5.0
  insight:
    version: 5.5.2

baseurl: /ome-help
clsbaseurl: /ome-help/cls
